package server_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync/atomic"
	"testing"

	"github.com/rilldata/rill/admin/testadmin"
	adminv1 "github.com/rilldata/rill/proto/gen/rill/admin/v1"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Valid subscription keys as generated by a browser's Push API (a P-256 point and a 16-byte auth secret).
const (
	testP256dh = "BNcRdreALRFXTkOOUHK1EtK2wtaz5Ry4YfYCA_0QTpQtUbVlUls0VJXg7A8u-Ts1XbjhazAkj7I99e8QcYP7DkM="
	testAuth   = "zqbxT6JKstKSY9JKibZLSQ=="
)

func TestPushSubscriptions(t *testing.T) {
	ctx := context.Background()
	fix := testadmin.New(t)

	u1, c1 := fix.NewUser(t)
	_, c2 := fix.NewUser(t)

	t.Run("Config returns the VAPID public key", func(t *testing.T) {
		res, err := c1.GetPushNotificationConfig(ctx, &adminv1.GetPushNotificationConfigRequest{})
		require.NoError(t, err)
		require.NotEmpty(t, res.VapidPublicKey)
	})

	t.Run("Subscription lifecycle", func(t *testing.T) {
		_, err := c1.CreatePushSubscription(ctx, &adminv1.CreatePushSubscriptionRequest{Endpoint: "https://push.example.com/lifecycle-1", P256Dh: testP256dh, Auth: testAuth, UserAgent: "Firefox"})
		require.NoError(t, err)
		_, err = c1.CreatePushSubscription(ctx, &adminv1.CreatePushSubscriptionRequest{Endpoint: "https://push.example.com/lifecycle-2", P256Dh: testP256dh, Auth: testAuth})
		require.NoError(t, err)

		res, err := c1.ListPushSubscriptions(ctx, &adminv1.ListPushSubscriptionsRequest{})
		require.NoError(t, err)
		require.Len(t, res.Subscriptions, 2)
		require.Equal(t, "https://push.example.com/lifecycle-1", res.Subscriptions[0].Endpoint)
		require.Equal(t, "Firefox", res.Subscriptions[0].UserAgent)

		// Another user can't delete someone else's subscription
		_, err = c2.DeletePushSubscription(ctx, &adminv1.DeletePushSubscriptionRequest{Id: res.Subscriptions[0].Id})
		require.Error(t, err)
		require.Equal(t, codes.NotFound, status.Code(err))

		_, err = c1.DeletePushSubscription(ctx, &adminv1.DeletePushSubscriptionRequest{Id: res.Subscriptions[0].Id})
		require.NoError(t, err)
		res, err = c1.ListPushSubscriptions(ctx, &adminv1.ListPushSubscriptionsRequest{})
		require.NoError(t, err)
		require.Len(t, res.Subscriptions, 1)

		_, err = c1.DeletePushSubscription(ctx, &adminv1.DeletePushSubscriptionRequest{Id: res.Subscriptions[0].Id})
		require.NoError(t, err)
	})

	t.Run("Preferences default to enabled and can be updated", func(t *testing.T) {
		res, err := c1.GetNotificationPreferences(ctx, &adminv1.GetNotificationPreferencesRequest{})
		require.NoError(t, err)
		require.True(t, res.Preferences.PushAlerts)
		require.True(t, res.Preferences.PushReports)
		require.True(t, res.Preferences.PushActApprovals)

		upd, err := c1.UpdateNotificationPreferences(ctx, &adminv1.UpdateNotificationPreferencesRequest{
			Preferences: &adminv1.NotificationPreferences{PushAlerts: false, PushReports: true, PushActApprovals: false},
		})
		require.NoError(t, err)
		require.False(t, upd.Preferences.PushAlerts)

		res, err = c1.GetNotificationPreferences(ctx, &adminv1.GetNotificationPreferencesRequest{})
		require.NoError(t, err)
		require.False(t, res.Preferences.PushAlerts)
		require.True(t, res.Preferences.PushReports)
		require.False(t, res.Preferences.PushActApprovals)

		// Restore defaults for the send tests below
		_, err = c1.UpdateNotificationPreferences(ctx, &adminv1.UpdateNotificationPreferencesRequest{
			Preferences: &adminv1.NotificationPreferences{PushAlerts: true, PushReports: true, PushActApprovals: true},
		})
		require.NoError(t, err)
	})

	t.Run("Send", func(t *testing.T) {
		// Mock push services: one delivers, one reports the subscription as gone
		var delivered atomic.Int32
		okSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			delivered.Add(1)
			w.WriteHeader(http.StatusCreated)
		}))
		defer okSrv.Close()
		goneSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusGone)
		}))
		defer goneSrv.Close()

		orgName := randomName()
		r1, err := c1.CreateOrganization(ctx, &adminv1.CreateOrganizationRequest{Name: orgName})
		require.NoError(t, err)
		r2, err := c1.CreateProject(ctx, &adminv1.CreateProjectRequest{Org: r1.Organization.Name, Project: "proj1", ProdSlots: 1, SkipDeploy: true})
		require.NoError(t, err)

		u3, c3 := fix.NewUser(t)
		_, err = c1.CreatePushSubscription(ctx, &adminv1.CreatePushSubscriptionRequest{Endpoint: okSrv.URL, P256Dh: testP256dh, Auth: testAuth})
		require.NoError(t, err)
		_, err = c3.CreatePushSubscription(ctx, &adminv1.CreatePushSubscriptionRequest{Endpoint: goneSrv.URL, P256Dh: testP256dh, Auth: testAuth})
		require.NoError(t, err)

		// A user without access to the project can't send
		_, err = c3.SendPushNotification(ctx, &adminv1.SendPushNotificationRequest{ProjectId: r2.Project.Id, Category: "alerts", RecipientEmails: []string{u1.Email}, Title: "Hi"})
		require.Error(t, err)
		require.Equal(t, codes.PermissionDenied, status.Code(err))

		// An absolute or protocol-relative link path is rejected
		for _, linkPath := range []string{"https://evil.example.com/x", "//evil.example.com/x", "relative/no/slash"} {
			_, err = c1.SendPushNotification(ctx, &adminv1.SendPushNotificationRequest{ProjectId: r2.Project.Id, Category: "alerts", RecipientEmails: []string{u1.Email}, Title: "Hi", LinkPath: linkPath})
			require.Error(t, err)
			require.Equal(t, codes.InvalidArgument, status.Code(err), "link_path %q", linkPath)
		}

		// An unknown category is rejected
		_, err = c1.SendPushNotification(ctx, &adminv1.SendPushNotificationRequest{ProjectId: r2.Project.Id, Category: "invalid", RecipientEmails: []string{u1.Email}, Title: "Hi"})
		require.Error(t, err)
		require.Equal(t, codes.InvalidArgument, status.Code(err))

		// A recipient that opted out of the category is skipped
		_, err = c3.UpdateNotificationPreferences(ctx, &adminv1.UpdateNotificationPreferencesRequest{
			Preferences: &adminv1.NotificationPreferences{PushAlerts: false, PushReports: true, PushActApprovals: true},
		})
		require.NoError(t, err)
		res, err := c1.SendPushNotification(ctx, &adminv1.SendPushNotificationRequest{
			ProjectId:       r2.Project.Id,
			Category:        "alerts",
			RecipientEmails: []string{u1.Email, u3.Email},
			Title:           "Alert fired",
			Body:            "Details",
			LinkPath:        "/" + orgName + "/proj1/-/alerts/a1",
			Tag:             "a1",
		})
		require.NoError(t, err)
		require.Equal(t, int32(1), res.Sent)
		require.Equal(t, int32(1), delivered.Load())

		// For a category the recipient did not opt out of, the gone subscription is contacted and purged
		res, err = c1.SendPushNotification(ctx, &adminv1.SendPushNotificationRequest{
			ProjectId:       r2.Project.Id,
			Category:        "reports",
			RecipientEmails: []string{u1.Email, u3.Email},
			Title:           "Your report is ready",
		})
		require.NoError(t, err)
		require.Equal(t, int32(1), res.Sent)
		require.Equal(t, int32(2), delivered.Load())
		subs, err := c3.ListPushSubscriptions(ctx, &adminv1.ListPushSubscriptionsRequest{})
		require.NoError(t, err)
		require.Len(t, subs.Subscriptions, 0)
	})
}
